---

# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=vagrant
ansible_become=true
#ansible_ssh_user=root
#openshift_disable_check=memory_availability,disk_availability,docker_storage,docker_image_availability

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become_user=vagrant

openshift_deployment_type=origin
openshift_repos_enable_testing=true
openshift_release=v3.9.0
openshift_disable_check=docker_storage,memory_availability,docker_image_availability
#containerized=true

#openshift_master_default_subdomain=lab.example.com
#openshift_docker_insecure_registries=172.30.0.0/16
#
## uncomment the following to enable htpasswd authentication; defaults to AllowAllPasswordIdentityProvider
##openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
#

## host group for masters
[masters]
master.lab.example.com openshift_schedulable=true containerized=false

# host group for etcd
[etcd]
master.lab.example.com

# host group for nodes, includes region info
[nodes]
master.lab.example.com openshift_node_group_name='node-config-master'
node1.lab.example.com openshift_node_group_name='node-config-compute'
node2.lab.example.com openshift_node_group_name='node-config-compute'
infra-node1.lab.example.com openshift_node_group_name='node-config-infra'

##openshift_schedulable=true

